# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.1
      with:
        files: '["**/WEB-INF/**"]'
    # - name: Build war with Ant
    #   run: |
    #     cd etc/build
    #     ant war
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/main
        publish_branch: main
